<?php
/**
 * @file
 * rollbar.module.
 */

/**
 * Helper function to get the path to the library.
 *
 * Since we include the Rollbar class at hook_boot, the module's
 * libraries havn't been loaded yet, so we must include them manually.
 */
function _rollbar_get_library_path() {
  return variable_get('rollbar_lib_path', 'sites/all/libraries/rollbar/rollbar.php');
}


/**
 * Implements hook_permission().
 */
function rollbar_permission() {
  return array(
    'administer rollbar' => array(
      'title' => t('Administer rollbar settings'),
      'description' => t('Allow user to administer all Rollbar settings.'),
    ),
  );
}


/**
 * Implements hook_requirements().
 */
function rollbar_requirements($phase) {
  $requirements = array();

  // Only runtime, we dont care about installation or update.
  if ($phase == 'runtime') {
    // Make sure the rollbar class exists. We don't check for the existence
    // of the class file here since it should always be included in hook_boot()
    // and should already have been called by now, since it's required on
    // every page request.
    if (!class_exists('Rollbar')) {
      $requirements['rollbar_library'] = array(
        'title' => t('Rollbar library is missing'),
        'description' => t(
          'The path to the Rollbar library is missing, see the
            README or !link.',
          array(
            '!link' => l(t('adjust your settings'), 'admin/config/development/rollbar'),
          )
        ),
        'value' => _rollbar_get_library_path(),
        'severity' => REQUIREMENT_WARNING,
      );
    }
    else {
      $requirements['rollbar_library'] = array(
        'title' => t('Rollbar library'),
        'value' => RollbarNotifier::VERSION,
        'severity' => REQUIREMENT_OK,
      );
    }

    if (variable_get('rollbar_enable_php', 1) == 1 && trim(variable_get('rollbar_server_access_token', '')) == '') {
      $requirements['rollbar_server_key'] = array(
        'title' => t('Rollbar PHP token missing.'),
        'description' => t(
          'Rollbar for PHP is enabled, however the access token is missing. Please !link.',
          array(
            '!link' => l(t('configure your settings'), 'admin/config/development/rollbar'),
          )
        ),
        'value' => 'Missing token',
        'severity' => REQUIREMENT_INFO,
      );
    }

    if (variable_get('rollbar_enable_js', 1) == 1 && trim(variable_get('rollbar_js_access_token', '')) == '') {
      $requirements['rollbar_client_key'] = array(
        'title' => t('Rollbar JS token missing.'),
        'description' => t(
          'Rollbar for JavaScript is enabled however the access token is missing. Please !link.',
          array(
            '!link' => l(t('configure your settings'), 'admin/config/development/rollbar'),
          )
        ),
        'value' => 'Missing token',
        'severity' => REQUIREMENT_INFO,
      );
    }
  }
  return $requirements;
}


/**
 * Implements hook_boot().
 */
function rollbar_boot() {

  // Return if PHP support is not enabled.
  if (variable_get('rollbar_enable_php', 0) != 1) {
    return;
  }

  // Load Rollbar settings from the Drupal variables table.
  $access_token = check_plain(variable_get('rollbar_server_access_token', ''));
  $environment = check_plain(variable_get('rollbar_environment', 'production'));
  $exceptions = check_plain(variable_get('rollbar_exceptions', 1));
  $errors = check_plain(variable_get('rollbar_error_handling', 1));

  // Get the path to the library.
  $rollbar_lib_path = _rollbar_get_library_path();

  // Make sure that the file exists before being included...
  if (!file_exists($rollbar_lib_path)) {

    // ...otherwise, attempt to load it via DRUPAL_ROOT. This is for some cases
    // where bootstrapped instances of the include path aren't set correctly.
    $rollbar_lib_path = DRUPAL_ROOT . '/' . $rollbar_lib_path;
    if (!file_exists($rollbar_lib_path)) {
      watchdog(
        'rollbar',
        'Unable to load Rollbar library. File @path does not exist. Please check your configuration settings.',
        array('@path' => $rollbar_lib_path),
        WATCHDOG_NOTICE
      );
    }
    return;
  }

  include_once $rollbar_lib_path;
  Rollbar::init(
    array(
      'access_token' => $access_token,
      'environment' => $environment,
      'person' => array(
        'id' => $GLOBALS['user']->uid,
        'username' => $GLOBALS['user']->name,
        'email' => $GLOBALS['user']->mail,
      ),
    ), $exceptions, $errors
  );
}


/**
 * Implements hook_watchdog().
 */
function rollbar_watchdog($log_entry) {

  // Return if the Rollbar is not set to pick up Watchdog messages.
  if (variable_get('rollbar_watchdog', 0) != 1) {
    return;
  }

  // Return If this is a PHP error and we haven't specifically chosen
  // to send these errors to Rollbar.
  if ($log_entry['type'] == 'php') {
    if (variable_get('rollbar_watchdog_include_php', '0') != 1) {
      return;
    }
  }

  // Map watchdog constants to strings for Rollbar.
  switch ($log_entry['severity']) {
    case WATCHDOG_ALERT:
    case WATCHDOG_CRITICAL:
    case WATCHDOG_EMERGENCY:
    case WATCHDOG_ERROR:
      $level = 'error';
      break;
    case WATCHDOG_WARNING:
      $level = 'warning';
      break;
    case WATCHDOG_INFO:
    case WATCHDOG_DEBUG:
    case WATCHDOG_NOTICE:
      $level = 'info';
      break;
    default:
      $level = 'info';
      break;
  }

  // Ensure that the Rollbar class exists; this is an additional check
  // in case hook_boot was unable to locate the Rollbar class.
  // This may happen if the user hasn't specified the correct path.
  if (class_exists('Rollbar')) {

    // Return if the Watchdog message contains our blacklisted strings.
    $blacklist = explode("\n", variable_get('rollbar_blacklist', ''));
    if (!empty($blacklist)) {
      foreach ($blacklist as $item) {
        if (stripos(trim($log_entry['message']), trim($item)) !== FALSE) {
          return;
        }
      }
    }

    // Send the message with some details from Watchdog.
    Rollbar::report_message(
      t($log_entry['message'], $log_entry['variables']),
      $level,
      array(
        'type' => $log_entry['type'],
        'uid' => $log_entry['uid'],
        'request_uri' => $log_entry['request_uri'],
        'referer' => $log_entry['referer'],
        'ip' => $log_entry['ip'],
      )
    );
  }
}


/**
 * Implements hook_init().
 *
 * This is used to attach the Javascript listeners to the page.
 */
function rollbar_init() {

  // Return if JS support is turned off.
  if (variable_get('rollbar_enable_js', 0) == 0) {
    return;
  }

  // Load client settings from Drupal variables.
  $token = check_plain(variable_get('rollbar_js_access_token', ''));
  $env = check_plain(variable_get('rollbar_environment', 'production'));

  // I had some issues appending this via jQuery and using Drupal.behaviors,
  // so have opted to use plain Javascript in line with the Rollbar.com
  // documentation. This is essentially an exact copy of the code
  // located at https://rollbar.com/docs/items_js.
  $js = "var _rollbarParams = {'server.environment': '$env'};" .
  "_rollbarParams['notifier.snippet_version'] = '2';" .
  "var _rollbar=['$token', _rollbarParams];" .
  "var _ratchet=_rollbar;(function(w,d){w.onerror=function(e,u,l) {" .
  "_rollbar.push({_t:'uncaught',e:e,u:u,l:l});};var i=function(){" .
  "var s=d.createElement('script');var f=d.getElementsByTagName('script')[0];" .
  "s.src='//d37gvrvc0wt4s1.cloudfront.net/js/1/rollbar.min.js';s.async=!0;" .
  "f.parentNode.insertBefore(s,f);};if(w.addEventListener){" .
  "w.addEventListener('load',i,!1);}else{w.attachEvent('onload',i);}" .
  "})(window,document);";

  // Add the Rollbar Javascript after Drupal's core JS and jQuery have been
  // loaded, but before everything else.
  drupal_add_js($js, array(
    'type' => 'inline',
    'scope' => 'header',
    'weight' => -99,
    'group' => JS_LIBRARY,
  ));
}


/**
 * Implements hook_menu().
 */
function rollbar_menu() {
  $items = array();
  $items['admin/config/development/rollbar'] = array(
    'title' => 'Rollbar settings',
    'description' => 'Make changes to your Rollbar settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rollbar_admin_settings_form'),
    'access arguments' => array('administer rollbar'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'rollbar.admin.inc',
  );
  return $items;
}
